module.exports = {
    FULL_NAME: "Full Name",
    EMAIL_ADDRESS: "Email Address",
    PASSWORD: "Password",
    REGISTER: "Register",
    CANCEL: "Cancel",
    SIGNIN: "Sign in",
    FORGOT_PASSWORD: "Forgot password?",
    CREATE_ACCOUNT: "Create an account",
    INSTAN: "instan",
    SIGNIN_ERROR: "Invalid User Name OR Password",
    LOADING: "Loading...",
    COMMON_ERROR_MESSAGE: "Opps..something went wrong",
    NETWORK_ERROR: "ERROR: Please check your internet connection..!",
    UPLOAD: "Upload",
    SIGNUP_ERROR: "Please provide name email and password",
    SHARE_MESSAGE: "Something interesting I hope you will definetly like it",
    PROFILE: "Profile",
    HOME: "Home",
    LOGOUT: "LOGOUT",
    SAVE: "SAVE",
    UPDATE_PROFILE: "UPDATE" 
};
